name: Check Website Performance with PageSpeed Insights

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Running Page Speed Insights
        uses: JakePartusch/psi-action@v1
        with:
          url: "https://ntlchs.github.io/"
          threshold: 60
          strategy: mobile
          key: ${{ secrets.PSI_API_KEY }}
